"""
graph_generator.py
Universal compiler and code-generator for recurrent graph execution in llama.cpp.
Translates topology specifications into optimized GGML computational graphs.
Supports Qwen2 and Focal architectures.
"""

import os
import subprocess
from typing import Dict, Any, List
from recurrent_engine.recurrent_spec import ArchitectureTopology, RecurrentLoopBlock, FeedForwardBlock

class RecurrentGraphCompiler:
    def __init__(self, llama_cpp_root: str = "/home/cune/llama.cpp", build_dir: str = "build-cuda-vnni"):
        self.root = os.path.abspath(llama_cpp_root)
        self.build_dir = os.path.join(self.root, build_dir)
        self.graph_cpp_path = os.path.join(self.root, "src/llama-graph.cpp")
        self.context_cpp_path = os.path.join(self.root, "src/llama-context.cpp")

    def generate_cpp_core_function(self, topology: ArchitectureTopology) -> str:
        """
        Generates a C++ GGML graph builder function tailored to the topology.
        """
        code = []
        code.append("// Auto-generated by RecurrentGraphCompiler for " + topology.architecture)
        code.append("ggml_tensor * build_custom_recurrent_graph(")
        code.append("        llm_graph_context & gf,")
        code.append("        ggml_tensor * inpL,")
        code.append("        const std::function<ggml_tensor * (int il, ggml_tensor * input)> & decoder,")
        code.append("        const std::function<void (int il, ggml_tensor * input)> & on_entry) {")
        
        loop_counter = 0
        for block in topology.blocks:
            if isinstance(block, FeedForwardBlock):
                lo, hi = block.layers[0], block.layers[1] if len(block.layers) > 1 else block.layers[0]
                code.append(f"    // Feedforward sequence [{lo}..{hi}]")
                code.append(f"    for (int il = {lo}; il <= {hi}; ++il) {{")
                code.append("        if (on_entry) on_entry(il, inpL);")
                code.append("        inpL = decoder(il, inpL);")
                code.append("    }")
            elif isinstance(block, RecurrentLoopBlock):
                loop_counter += 1
                lo, hi = block.layers[0], block.layers[1] if len(block.layers) > 1 else block.layers[0]
                t_val = block.iterations
                a_val = block.recurrent_a
                b_val = block.recurrent_b
                gate_val = block.recurrent_gate
                eps = block.norm_eps

                # Precompute dynamic parameter schedules
                import math
                def evaluate_schedule(sched_str: str, T: int) -> List[float]:
                    s = sched_str.strip()
                    if s.startswith("linear"):
                        args = [float(x.strip()) for x in s[s.find("(")+1:s.rfind(")")].split(",")]
                        start, end = args[0], args[1]
                        return [start + t * (end - start) / max(1, T - 1) for t in range(T)]
                    elif s.startswith("cosine"):
                        args = [float(x.strip()) for x in s[s.find("(")+1:s.rfind(")")].split(",")]
                        start, end = args[0], args[1]
                        return [end + 0.5 * (start - end) * (1.0 + math.cos(math.pi * t / max(1, T - 1))) for t in range(T)]
                    elif s.startswith("exponential") or s.startswith("exp"):
                        args = [float(x.strip()) for x in s[s.find("(")+1:s.rfind(")")].split(",")]
                        start, decay = args[0], args[1]
                        return [start * (decay ** t) for t in range(T)]
                    return [float(s)] * T

                code.append(f"    // Recurrent Loop: {block.name} [{lo}..{hi}], T={t_val}")
                code.append(f"    ggml_tensor * anchor = inpL;")
                code.append(f"    ggml_tensor * h = inpL;")

                for p_name, p_sched in block.schedules.items():
                    vals = evaluate_schedule(p_sched, t_val)
                    c_vals = ", ".join(f"{v:.6f}f" for v in vals)
                    code.append(f"    const float {p_name}_sched[{t_val}] = {{ {c_vals} }}; // {p_sched}")

                # Initialize any custom auxiliary state registers (e.g. momentum v)
                for st in block.state_tensors:
                    code.append(f"    ggml_tensor * {st} = ggml_scale(gf.ctx0, inpL, 0.0f); // zero-initialized register")

                code.append(f"    for (int t = 0; t < {t_val}; ++t) {{")
                # Bind scheduled parameters at iteration t
                for p_name in block.schedules.keys():
                    code.append(f"        const float {p_name} = {p_name}_sched[t];")
                code.append(f"        ggml_tensor * combined = ggml_rms_norm(gf.ctx0,")
                code.append(f"                ggml_add(gf.ctx0, h, anchor), {eps}f);")
                code.append("        ggml_tensor * cur = combined;")
                for il in range(lo, hi + 1):
                    code.append(f"        if (on_entry) on_entry({il}, cur);")
                    code.append(f"        cur = decoder({il}, cur);")
                code.append("        ggml_tensor * block_out = cur;")

                if block.custom_formulas:
                    from recurrent_engine.math_ast import GGMLMathCompiler
                    math_comp = GGMLMathCompiler(ctx_name="gf.ctx0", default_eps=eps)
                    env_tensors = {"h", "anchor", "combined", "block_out"}.union(block.state_tensors)
                    scalar_params = {
                        "a": a_val,
                        "b": b_val,
                        "gamma": gate_val,
                        "recurrent_a": a_val,
                        "recurrent_b": b_val,
                        "recurrent_gate": gate_val,
                    }
                    scalar_params.update(block.custom_params)
                    for sp in block.schedules.keys():
                        scalar_params.pop(sp, None)
                    math_comp.set_environment(
                        tensor_vars=env_tensors,
                        scalar_params=scalar_params,
                        scheduled_vars=set(block.schedules.keys())
                    )
                    compiled_math = math_comp.compile_block(block.custom_formulas)
                    code.append(f"        // Custom Mathematical Theory Update Rule:\n{compiled_math}")
                else:
                    if block.delta_mode in ("pure_delta", "double_residual"):
                        # Pure delta fix: isolate nonlinear transformation delta = block_out - combined = G(combined)
                        code.append("        ggml_tensor * delta_thought = ggml_sub(gf.ctx0, block_out, combined);")
                    else:
                        code.append("        ggml_tensor * delta_thought = block_out;")
                    code.append(f"        h = ggml_add(gf.ctx0,")
                    code.append(f"                ggml_add(gf.ctx0, ggml_scale(gf.ctx0, h, {a_val}f), ggml_scale(gf.ctx0, anchor, {b_val}f)),")
                    code.append(f"                ggml_scale(gf.ctx0, delta_thought, {gate_val}f));")

                code.append("    }")
                code.append("    inpL = h;")

        code.append("    return inpL;")
        code.append("}")
        return "\n".join(code)

    def extract_runtime_cli_args(self, topology: ArchitectureTopology) -> List[str]:
        """
        Converts topology into dynamic llama-cli / llama-bench flags for the current build.
        """
        for block in topology.blocks:
            if isinstance(block, RecurrentLoopBlock):
                lo = block.layers[0]
                hi = block.layers[1] if len(block.layers) > 1 else block.layers[0]
                return [
                    f"--recurrent-layer", str(lo),
                    f"--recurrent-layer-b", str(hi),
                    f"--recurrent-t", str(block.iterations),
                    f"--recurrent-a", f"{block.recurrent_a:.2f}",
                    f"--recurrent-b", f"{block.recurrent_b:.2f}",
                    f"--recurrent-gate", f"{block.recurrent_gate:.2f}",
                ]
        return ["--recurrent-t", "1"]

    def build_binaries(self, targets: List[str] = None) -> bool:
        """
        Invokes cmake to compile specified binaries.
        """
        if targets is None:
            targets = ["llama-cli", "llama-bench", "llama-perplexity"]
        cmd = ["cmake", "--build", self.build_dir, "--target"] + targets + ["-j4"]
        print(f"Executing: {' '.join(cmd)}")
        res = subprocess.run(cmd, cwd=self.root)
        return res.returncode == 0
